### ISSUE TITLE
Adaway  can't grab file

### ISSUE THREAD

**Issue by ghost** [JasonD94/android-hosts#1]
Somehow Adaway can not grab the file from https://raw.githubusercontent.com/JasonD94/android-hosts/master/hosts.txt

Any suggestions?
All my other hosts sources get loaded.

**Comment by ghost** [comment]
Adaway status for the file is local: not available / online: not available

**Comment by polygon21** [comment]
Same, able to download the txt using chrome but adaway can't seem to download the link

**Comment by JasonD94** [comment]
I don't use AdAway currently, as my current Android phone is not rooted. However, [DNS66](https://github.com/julian-klode/dns66) was able to find the URL and loaded it without issue. 

I remember running into a similar issue when I was using AdAway. I found an issue on StevenBlack's hosts repository that I even commented on (my old phone was rooted and had AdAway installed) with the following comment:

> This seems to be a bug with AdAway. It doesn't seem to show any GitHub URLs as being available. I've added my own hosts file for blocking Spotify ads and it does the same thing - "Local: not available, Online: not available".
> However, since I've added my own hosts file I haven't gotten a single Spotify ad. So I'm willing to guess that it shows "not available" but can still access the hosts file and merge it. I've also noticed it shows the right number of sources applied, even if a few (such as the hosts file for this repo) show up as "not available" in the app.

[You can find the Github Issue I mentioned above here.](https://github.com/StevenBlack/hosts/issues/188) I'm guessing it's the same issue as before, which is a bug with AdAway that is causing it to not recognize raw.githubusercontent.com links as valid. Since this isn't an issue with my hosts file (nor with StevenBlack's), I suggest you make an issue on [AdAway's GitHub repo](https://github.com/AdAway/AdAway). They may have more insight into why raw.githubusercontent.com URLs fail.

**Comment by JasonD94** [comment]
Closing this issue because it's not really an issue with my hosts file, but instead an issue with AdAway or Github raw URLs not being supported by AdAway for some unknown reason. [DNS66](https://github.com/julian-klode/dns66) works with the android-hosts file, so that is another alternative to try.
